BOOTBUILD = bootloader/build
KERNELBUILD = kernel/build

GCCDIR = /home/arch/code/StonerOS/gcc
CXX32 = $(GCCDIR)/i386-elf/bin/i386-elf-g++
LD = $(GCCDIR)/i386-elf/bin/i386-elf-ld

CFLAGS = -ffreestanding -fno-stack-protector -m32
